class_name Tuning
extends RefCounted

const MATCH_SECONDS := 180.0
const SCORE_PER_SECOND := 1

const PLAYER_MOVE_SPEED := 6.0
const PLAYER_ACCELERATION := 18.0
const PLAYER_TURN_SPEED := 10.0
const JUMP_VELOCITY := 5.0

const LUNGE_FORCE := 12.0
const LUNGE_DURATION := 0.22
const LUNGE_COOLDOWN := 0.85
const KNOCKOFF_IMPACT_THRESHOLD := 9.0
const FALL_KNOCKOFF_TILT_DOT := 0.45
const FALL_KNOCKOFF_COOLDOWN := 1.25

const CARRIER_SPEED_MULTIPLIER := 0.8
const CARRIER_STABILITY_MULTIPLIER := 0.85

const HEAD_PICKUP_RADIUS := 1.6
const HEAD_RESET_SECONDS := 8.0
const HEAD_OUT_OF_BOUNDS_Y := -8.0
const HEAD_MAX_ROLL_SPEED := 12.0

const BOT_MOVE_SPEED := 5.2
const BOT_CHASE_DISTANCE := 18.0
const BOT_LUNGE_RANGE := 2.2
const BOT_LUNGE_INTERVAL := 1.4
const BOT_REPATH_INTERVAL := 0.25
const BOT_RECOVER_SECONDS := 0.8
